exports.DraftRawContent = {
  blocks: [
    {
      key: "akcjv",
      text: "Date",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [
        { offset: 0, length: 4, style: "color-rgb(56,56,56)" },
        { offset: 0, length: 4, style: "fontsize-14" },
        {
          offset: 0,
          length: 4,
          style:
            'fontfamily--apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',
        },
        { offset: 0, length: 4, style: "fontfamily-Helvetica Neue" },
      ],
      entityRanges: [],
      data: { "text-align": "start" },
    },
    {
      key: "2dp8f",
      text: "Time",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [
        { offset: 0, length: 4, style: "color-rgb(56,56,56)" },
        { offset: 0, length: 4, style: "fontsize-14" },
        {
          offset: 0,
          length: 4,
          style:
            'fontfamily--apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',
        },
        { offset: 0, length: 4, style: "color-rgb(153,153,153)" },
        { offset: 0, length: 4, style: "fontfamily-Helvetica Neue" },
      ],
      entityRanges: [],
      data: { "text-align": "start" },
    },
    {
      key: "9onli",
      text: "\n",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: { "text-align": "start" },
    },
    {
      key: "85p76",
      text: "Location",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [
        { offset: 0, length: 8, style: "color-rgb(56,56,56)" },
        { offset: 0, length: 8, style: "fontsize-14" },
        {
          offset: 0,
          length: 8,
          style:
            'fontfamily--apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',
        },
        { offset: 0, length: 8, style: "fontfamily-Helvetica Neue" },
        { offset: 0, length: 8, style: "BOLD" },
      ],
      entityRanges: [],
      data: { "text-align": "start" },
    },
    {
      key: "8b4s5",
      text: "\n",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: { "text-align": "start" },
    },
    {
      key: "fvjbv",
      text: "Participants",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [
        { offset: 0, length: 12, style: "color-rgb(56,56,56)" },
        { offset: 0, length: 12, style: "fontsize-14" },
        {
          offset: 0,
          length: 12,
          style:
            'fontfamily--apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',
        },
        { offset: 0, length: 12, style: "fontfamily-Helvetica Neue" },
        { offset: 0, length: 12, style: "BOLD" },
      ],
      entityRanges: [],
      data: { "text-align": "start" },
    },
    {
      key: "1ta2s",
      text: "\n",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: { "text-align": "start" },
    },
    {
      key: "43pjv",
      text: "Description",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [
        { offset: 0, length: 11, style: "color-rgb(56,56,56)" },
        { offset: 0, length: 11, style: "fontsize-14" },
        {
          offset: 0,
          length: 11,
          style:
            'fontfamily--apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',
        },
        { offset: 0, length: 11, style: "fontfamily-Helvetica Neue" },
        { offset: 0, length: 11, style: "BOLD" },
      ],
      entityRanges: [],
      data: { "text-align": "start" },
    },
    {
      key: "auqlr",
      text: "\n",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: { "text-align": "start" },
    },
    {
      key: "adgac",
      text: "Notes",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [
        { offset: 0, length: 5, style: "color-rgb(56,56,56)" },
        { offset: 0, length: 5, style: "fontsize-14" },
        {
          offset: 0,
          length: 5,
          style:
            'fontfamily--apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',
        },
        { offset: 0, length: 5, style: "fontfamily-Helvetica Neue" },
        { offset: 0, length: 5, style: "BOLD" },
      ],
      entityRanges: [],
      data: { "text-align": "start" },
    },
    {
      key: "d8ijh",
      text: "\n",
      type: "unordered-list-item",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: { "margin-left": "0px" },
    },
    {
      key: "8gnd1",
      text: "\n",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: { "text-align": "start" },
    },
    {
      key: "4pkhk",
      text: "Next Steps",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [
        { offset: 0, length: 10, style: "color-rgb(56,56,56)" },
        { offset: 0, length: 10, style: "fontsize-14" },
        {
          offset: 0,
          length: 10,
          style:
            'fontfamily--apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',
        },
        { offset: 0, length: 10, style: "fontfamily-Helvetica Neue" },
        { offset: 0, length: 10, style: "BOLD" },
      ],
      entityRanges: [],
      data: { "text-align": "start" },
    },
    {
      key: "avpdu",
      text: " ",
      type: "unstyled",
      depth: 0,
      inlineStyleRanges: [],
      entityRanges: [],
      data: { "text-align": "start" },
    },
  ],
  entityMap: {},
};
